<form method="post" action="index.php?url=login/alterarsenhainicial" >
    <label class="formtopo">
        Senha nova<br>
        <input type="password" name="nova" id="texto"  class="form-control ">
    </label>
    <label class="formtopo">
        Repita a senha nova<br>
        <input type="password" name="rnova" id="texto"  class="form-control ">
    </label>
    <input type="submit" class="btn btn-primary"  >
</form>