<form method="post" action="index.php?url=login/mlogin" class="col-mx-2" >
    <label class="formtopo">
        Login<br>
        <input type="text" name="login" id="texto"  class="form-control">
    </label>
    <label class="formtopo">
        Senha<br>
        <input type="password" name="senha" id="texto"  class="form-control">
    </label>
  
    <input type="submit" class="btn btn-primary" >

</form>