<form method="post" action="index.php?url=cadastro/triagistafim">
    <label class="formtopo">
        Nome<br>
        <input type="text" name="nome" id="texto"  class="form-control " required>
    </label>
    <label class="formtopo">
        Email<br>
        <input type="email" name="login" id="texto"  class="form-control " required>
    </label>
    <label class="formtopo">
        Senha<br>
        <input type="password" name="senha" id="texto"  class="form-control " required>
    </label>
    <label class="formtopo">
        Confirmar senha<br>
        <input type="password" name="csenha" id="texto"  class="form-control " required>
    </label>
    <label class="formtopo">
        <input type="radio" name="tipo" id="texto"   required value="2">
        Triagista
    </label>
    <label class="formtopo">
        <input type="radio" name="tipo" id="texto"   required value="3">
        Administrador
    </label>
    <input type="submit" class="btn btn-primary"  >

</form>