
<h1>Candidato Aprovado</h1>
<table class="table table-condensed">
    <tr>
        <th>Id</th>
        <th>Nome</th>
        <th>Segmento</th>
    </tr>
    <?php
    if (isset($dadoscepc[3])) {
        foreach ($dadoscepc[3][3] as $key => $value) {
            foreach ($value as $value2) {
                echo "<tr>";
                echo "<td>{$value2->getId()}</td>";
                echo "<td>{$value2->getNome()}</td>";
                echo "<td>{$key}</td>";
                echo "</tr>";
            }
        }
    }
    ?>
</table>
<h1>Candidato Reprovado</h1>
<table class="table table-condensed">
    <tr>
        <th>Id</th>
        <th>Nome</th>
        <th>Segmento</th>
    </tr>
    <?php
    if (isset($dadoscepc[3])) {
        foreach ($dadoscepc[3][2] as $key => $value) {
            foreach ($value as $value2) {
                echo "<tr>";
                echo "<td>{$value2->getId()}</td>";
                echo "<td>{$value2->getNome()}</td>";
                echo "<td>{$key}</td>";
                echo "</tr>";
            }
        }
    }
    ?>
</table>
<h1>Eleitor Aprovado</h1>
<table class="table table-condensed">
    <tr>
        <th>Id</th>
        <th>Nome</th>
        <th>Segmento</th>
    </tr>
    <?php
    if (isset($dadoscepc[3])) {
        foreach ($dadoscepc[3][1] as $key => $value) {
            foreach ($value as $value2) {
                echo "<tr>";
                echo "<td>{$value2->getId()}</td>";
                echo "<td>{$value2->getNome()}</td>";
                echo "<td>{$key}</td>";
                echo "</tr>";
            }
        }
    }
    ?>
</table>
<h1>Eleitor Reprovado</h1>
<table class="table table-condensed">
    <tr>
        <th>Id</th>
        <th>Nome</th>
        <th>Segmento</th>
    </tr>
    <?php
    if (isset($dadoscepc[3])) {
        foreach ($dadoscepc[3][0] as $key => $value) {
            foreach ($value as $value2) {
                echo "<tr>";
                echo "<td>{$value2->getId()}</td>";
                echo "<td>{$value2->getNome()}</td>";
                echo "<td>{$key}</td>";
                echo "</tr>";
            }
        }
    }
    ?>
</table>