<?php
//$p[] = new Triagista($id, $nome, $sagmento);
$p = $dadoscepc[3];
?>
<h1>Lista de Retriagem</h1>
<h2 class="toph2">Total de inscrito: <?php echo $dadoscepc[5];?></h2>
<table class="table table-condensed">
    <tr>
        <th>Id</th>
        <th>Nome</th>
        <th>Segmento</th>
        <th>Situa&ccedil;&atilde;o</th>
        <th>Ver</th>
    </tr>
    <?php
    if (!empty($p)) {


        foreach ($p as $value) {
            echo '<tr>';
            echo "<td>{$value->getIdusuario()}</td>";
            echo "<td>{$value->getNome()}</td>";
            echo "<td>{$value->getSegmento()->getNome()}</td>";
            if ($value->getStatus() == 1) {
                echo "<td><a href='index.php?url=triage/retriar/{$value->getId()}'>retriar</a></td>";
            } elseif ($value->getStatus() < -1) {
                echo "<td>Retriando</td>";
            } else {
                echo "<td>Retriado</td>";
            }
            echo "<td><a href='index.php?url=triage/ver/{$value->getId()}'>ver</a></td>";
            echo '</tr>';
        }
    }
    ?>

</table>
<?php echo $dadoscepc[4]; ?>  