<form method="post" action="index.php?url=triage/triarfim">
    <label class="formtopo2"><input type="radio"  name="tipo" class="usuario"  required value="0">APROVADO</label>
    <label class="formtopo2"><input type="radio"  name="tipo" class="usuario"  required value="1">REPROVADO</label>
    <label class="formtopo">
        JUSTIFICATIVA<br>
        <textarea name="justificativa" id="texto" rows="8" required></textarea>
    </label>

    <input type="submit" class="btn btn-primary"  >

</form>